# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pirátská strana | RpR
email: to@pirati.cz
description: > # this means to ignore newlines until "baseurl:"
  Web Pirátů z Rožnova pod Radhoštěm.
url: "https://roznov.pirati.cz" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-sitemap
paginate_path: "/aktuality/:num/"
paginate: 11

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock

sass:
    style: compressed

permalink: /aktuality/:title.html
collections:
  people:
    output: true
    permalink: /lide/:path/
  program:
    output: true
    permalink: /volby-2018/:path/
  teams:
    output: true
    permalink: /pripoj-se/:title/

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_people"
    values:
      layout: "member"
      rbar: "foto"
  -
    scope:
      path: "_program"
    values:
      layout: "page"
      rbar: "volby-2018"
  -
    scope:
      path: "_teams"
    values:
      layout: "team"
      rbar: "team-summary, teams-toc"

emptyArray: []
exclude: [vendor]
